### ISSUE TITLE
iOS Integeration with Angular / ionic hybrid framework

### ISSUE THREAD

**Issue by mukesh123** [payu-intrepos/iOS-SDK#1]
Hi, 

I am trying to integrate the payu payment gateway with my ios mobile app built using ionic and angular js framework.

Is there is any way or steps to integrate this payu sdk with the ios ionic application?

Thanks
Frederic Anand

**Comment by umangarya336** [comment]
Please drop mail mobile.integration@payu.in if issue still exists.
