### ISSUE TITLE
V 3.7.3 does not contain a sample app

### ISSUE THREAD

**Issue by shubhsin** [payu-intrepos/iOS-SDK#10]
Issues with pod install and configure. Please provide a sample app with v3.7.3 to rectify them. Sample app should have details on how to get success response from the webview

**Comment by umangarya336** [comment]
To get success/failure response, Please integrate CustomBrowser
Documentation: https://app.gitbook.com/@payumobile/s/sdk-integration/ios/ios-custom-browser

Please drop mail mobile.integration@payu.in if issue still exists.
