### ISSUE TITLE
In webServiceResponse  paymentRelatedDetail object didn't contain any value

### ISSUE THREAD

**Issue by Sibasish1992** [payu-intrepos/iOS-SDK#11]
![screen shot 2017-01-23 at 10 53 09 am](https://cloud.githubusercontent.com/assets/23030525/22192464/6aab91d4-e15a-11e6-9435-42b95854decb.png)

**Comment by Sibasish1992** [comment]
@AshishPayU need help in this issue

**Comment by umangarya336** [comment]
Please try and integrate latest version of SDK 4.1.0
Please drop mail mobile.integration@payu.in if issue still exists.
