### ISSUE TITLE
Error in WebResponse getPayUPaymentRelatedDetail

### ISSUE THREAD

**Issue by hemanth2k13** [payu-intrepos/iOS-SDK#13]
Code for web response:
 
let webResponse = PayUWebServiceResponse()
        
        webResponse.getPayUPaymentRelatedDetail(forMobileSDK: params) { (paymentDetail, errorMessage, extraParam) in
            print(paymentDetail as Any)
            print(errorMessage as Any)
            print(extraParam as Any)
            if !(errorMessage != nil){
                let paymentVC = UIStoryboard(name: "PUUIMainStoryBoard", bundle: nil).instantiateViewController(withIdentifier: VC_IDENTIFIER_PAYMENT_OPTION) as! PUUIPaymentOptionVC
                paymentVC.paymentParam = self.params
                paymentVC.paymentRelatedDetail = paymentDetail
                var paymentNavController : UINavigationController;
                paymentNavController = UINavigationController(rootViewController: paymentVC);
                self.present(paymentNavController, animated: true, completion: nil)
            }else{
                print(errorMessage!)
            }
        }

Response Or Error:

2017-02-23 17:56:37.313913 CareForSure[916:362190] -[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.
nil
Optional("The data couldn’t be read because it isn’t in the correct format.")
Optional({
    PostParam = "instrument_id=C5A3749D-ECCE-4231-B74F-273798BB8DAC&instrument_type=iOS&device_type=2&key=40747T&command=payment_related_details_for_mobile_sdk&var1=&hash=302bc6e12fc6324aecbab4827717a5cc19965c2e80efb42668e8aebf6557a37282439a743b2dde27e375959735befa69e38fda7107b4682124d288b2b009f0b5";
})

Which data is not in correct format?

**Comment by akashrastogi** [comment]
Am also facing same issue.
`[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.
Payment Error- Optional("The data couldn’t be read because it isn’t in the correct format.")`

**Comment by Pulkit29** [comment]
Does anyone able to solve this out? 
I am also facing same issue. Please help if you can.

Thanks

**Comment by vipin04** [comment]
Hi Pulkit29,

Kindly check the key environment combination you are using. You get this kind of error when you are using prod-key with test environment or test-key with prod environment.

**Comment by gaus55** [comment]
I also get the same error but I belive that all tesk key and production are same now in payUmoney

**Comment by PravinNagargoje** [comment]
I'm getting same error. I'm using swift SDK. Everything seems fine key also. But after getting this error app crashes saying 'unexpectedly found nil value while unwrapping optional value'.

**Comment by SaoudSalih** [comment]
I also get the same error..does any one know  how to fix it?

**Comment by amberkatyal** [comment]
Yes indeed it is correct, it occurs when environment type doesn't matches with merchant key. It was happening for me only in testing. Make sure for testing environment it is ENVIRONMENT_TEST not mobile_test or mobile_dev

`#define ENVIRONMENT_PRODUCTION                                  @"Production"
#define ENVIRONMENT_MOBILETEST                                  @"MobileTest"
#define ENVIRONMENT_MOBILEDEV                                   @"MobileDev"
#define ENVIRONMENT_DEMOTEST                                    @"DemoTest"
#define ENVIRONMENT_TEST                                        @"Test"`
