### ISSUE TITLE
PlugNPlay.framework is giving an error for the project which is build using Xcode 9.2/9.1 with swift version 3.2

### ISSUE THREAD

**Issue by RohanJain70** [payu-intrepos/iOS-SDK#14]
I am trying to integrate PayUMoney with the help of latest PlugNPlay framework. But when I try to build the app it is giving me an error saying the <**PlugNPlay.framework** >module is complied with swift 4.0 and its cannot be imported in Swift 3.2 and also I tried downloading the older version of PayUMoney iOS SDK which contains older PlugNPlay framework but still it is giving me the similar issue.

**Comment by umangarya336** [comment]
This is ABI compatible issue.
This issue is fixed in our latest version of PlugNPlay
Please drop mail mobile.integration@payu.in if issue still exists.
