### ISSUE TITLE
Crash in Xcode 10.1 [IPAD] : [PayUCreateRequest setAnalyticsParam]

### ISSUE THREAD

**Issue by chetan-arvindinternet** [payu-intrepos/iOS-SDK#17]
crashing in latest Xcode 10.1 and IPAD (12.1), Strangely works in iPhone

This works in older versions of Xcode. Please check on priority

<<attached screen shot of the crash log >>

<img width="1410" alt="screenshot 2019-01-23 at 19 50 39" src="https://user-images.githubusercontent.com/42667971/51613267-21b38e80-1f49-11e9-9e22-7a8262c2b905.png">

**Comment by umangarya336** [comment]
I hope this issue is fixed in our latest version 4.1.0
Please drop mail mobile.integration@payu.in if issue still exists.
