### ISSUE TITLE
v3.9.3 does not contain a sample app

### ISSUE THREAD

**Issue by karthikmandava7** [payu-intrepos/iOS-SDK#21]
There is no sample app for the latest versions and raised the issue in other threads. It's mandatory to update the sample Apps as the latest versions have WKWebview but there is no sample App with the WKWebView which is causing the integrating the latest versions.

https://github.com/payu-intrepos/iOS-SDK-Sample-App/issues/16

**Comment by karthikmandava7** [comment]
what is the equivalent of PayUWebViewResponse in WKWebView with Custom Browser?

**Comment by umangarya336** [comment]
You can get the surl/furl response from CustomBrowser.
