### ISSUE TITLE
dyld: Library not loaded: @rpath/PayUBizCoreKit.framework/PayUBizCoreKit

### ISSUE THREAD

**Issue by jamneeley** [payu-intrepos/iOS-SDK#23]
After dragging the framework into project and triple checking its added correctly in the general build phases tabs of the target I get this error after successfully building to a simulator.

dyld: Library not loaded: @rpath/PayUBizCoreKit.framework/PayUBizCoreKit
  Reason: image not found

This same thing happens with the Custom Browser framework. 

when trying to access PayUBizCoreKit.framework/PayUBizCoreKit manually it says it's damaged.

**Comment by b1nhle** [comment]
The issue is still happening in newest verson 6.2.0!
Could someone look at it again?

**Comment by ShubhGar** [comment]
Are you using manual or Cocoapods? Please use Cocoapods.

**Comment by JavierLaguna** [comment]
I have the same issue with this error
`dyld[10359]: Library not loaded: @rpath/PayUNetworkReachability.framework/PayUNetworkReachability`

Im integrating the SDK 6.4.0 manually and trying on xcode 12.5.1 and 13.1 with the same issue

**Comment by ShubhGar** [comment]
you also need to add PayUNetworkReachability framework

**Comment by JavierLaguna** [comment]
Then this documentation [https://payumobile.gitbook.io/sdk-integration/ios/core/core-sdk](url) is incomplete/outdated because I had to add PayUNetworkReachability and PayUParamsKit frameworks manually to the project and the documentation only says `Drag and drop PayUBizCoreSDK.framework into your project`

Thank you!

**Comment by ShubhGar** [comment]
Because we are supporting with cocoapods.
