### ISSUE TITLE
Invalid hash "getPayUPaymentRelatedDetail"

### ISSUE THREAD

**Issue by nagarro-mohitpadalia** [payu-intrepos/iOS-SDK#25]
Hi,

When we don't set the userCredentials property in payment parameters, we get the error "Invalid hash". In this case the request ise sent as:

url:
https://info.payu.in/merchant/postservice.php?form=2
post params:
instrument_id=12345678&instrument_type=iOS&device_type=2&key={key}&command=payment_related_details_for_mobile_sdk&var1=&hash={hash}

You can see that the var1 parameter is empty in this request whereas the value in this case for the var1 parameter should be "default".

From the SDK sample code we see that the var1 parameter contains the value for the userCredentials property set in the payment params. The request in this case becomes:

url:
https://info.payu.in/merchant/postservice.php?form=2
post params:
instrument_id=12345678&instrument_type=iOS&device_type=2&key=0MQaQP&command=payment_related_details_for_mobile_sdk&var1=merchantKey:uniqueUserIDAtMerchantEnd&hash=ff681ec4509da166df5d7e620644a8b7b6db36f5c43827e1daf1dcfe8ecfbac630e0a7b1ed6109426f3a7ef39f3953cb866466cc79b8119612e5d89c056dc7d0

Can you please investigate this and fix the issue.

Thanks

**Comment by ShubhGar** [comment]
Please use default in place of the blank.
