### ISSUE TITLE
Getting warning using xcode 7.3, please check the bold line for the reason

### ISSUE THREAD

**Issue by InderKumarRathore** [payu-intrepos/iOS-SDK#6]
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUWebViewResponse.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/Foundation-1YMZJBNB8N25F.pcm: No such file or directory
## note: Module debugging should be disabled when shipping static libraries.

while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUWebViewResponse.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/JavaScriptCore-3HTHDXZCTZ4Z3.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUWebViewResponse.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/WebKit-22BKFHMUCITVJ.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUWebViewResponse.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/ObjectiveC-1AJ1UYHO2U5H0.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUWebViewResponse.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/UIKit-28BB49EGP5YVQ.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUDontUseThisClass.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/Darwin-14BLQGFOQ69OU.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUUtils.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/SystemConfiguration-18L1HV6BPBDA6.pcm: No such file or directory
while processing /data/aspiring-minds/code/myamcat-ios/MyAmcat/ThirdPartySdk/PayUMoney/libPayU_iOS_CoreSDK.a(PayUUtils.o):
warning: /var/folders/70/zkgqs8j115510rsjhww8cqprw3y9yz/C/org.llvm.clang.943663071/ModuleCache/1YEYOO69Y4ENZ/CoreFoundation-14MC06FO67EMZ.pcm: No such file or directory

**Comment by InderKumarRathore** [comment]
Similar to this issue : https://github.com/mapbox/mapbox-gl-native/issues/4338

**Comment by InderKumarRathore** [comment]
Still these warning seems like we have to kick PayU sdk from the payment. No response from your side.

**Comment by hemanth2k13** [comment]
Hi, Found the reason for these warnings??? Possibly Crashlytics is not working because of this. Fabric always says Missing dSYMs.
