### ISSUE TITLE
PayUBizz giving error while integrating with Swift

### ISSUE THREAD

**Issue by amitgajjar510** [payu-intrepos/iOS-SDK#9]
It gives error "AppDelegate.h file not found".
Kindly give thoughts on this as I want to integrate PayUBizz in my swift project.

Thanks in advance.

**Comment by AshishPayU** [comment]
pls drop a mail at mobile-integration@payu.in

**Comment by umangarya336** [comment]
"AppDelegate.h" is a part of your app
Kindly check your app settings.
